// flow-typed signature: 22b170bbf19f4ebdbd6783a1ee6ffa20
// flow-typed version: <<STUB>>/babel-plugin-loop-optimizer_v1.4.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-loop-optimizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-loop-optimizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-loop-optimizer/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-loop-optimizer/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-loop-optimizer/lib/index'>;
}
