// flow-typed signature: 067d99ca9e640595130c20681a47aef0
// flow-typed version: <<STUB>>/babel-plugin-minify-constant-folding_v0.4.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-minify-constant-folding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-minify-constant-folding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-minify-constant-folding/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-minify-constant-folding/lib/replacements' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-minify-constant-folding/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-minify-constant-folding/lib/index'>;
}
declare module 'babel-plugin-minify-constant-folding/lib/replacements.js' {
  declare module.exports: $Exports<'babel-plugin-minify-constant-folding/lib/replacements'>;
}
