// flow-typed signature: a7e5c9ec2b767d13ba7012c6ccbdc2e4
// flow-typed version: <<STUB>>/babel-plugin-closure-elimination_v1.3.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-closure-elimination'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-closure-elimination' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-closure-elimination/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-closure-elimination/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-closure-elimination/lib/index'>;
}
