// flow-typed signature: 60f914885f82c6528f785667495eadb7
// flow-typed version: <<STUB>>/browser-process-hrtime_v^1.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-process-hrtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-process-hrtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'browser-process-hrtime/index' {
  declare module.exports: $Exports<'browser-process-hrtime'>;
}
declare module 'browser-process-hrtime/index.js' {
  declare module.exports: $Exports<'browser-process-hrtime'>;
}
