/**
 * Stub type definitions for WASM module
 * 
 * This file provides minimal type definitions when the actual WASM module
 * is not available (e.g., in CI before building, or during development).
 * The real types are generated by wasm-pack when building the WASM module.
 */

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
}

/**
 * Stub CPU6502 class that matches the WASM interface
 */
export class CPU6502 {
    constructor();
    free(): void;
    
    // Core operations
    reset(): void;
    step(): number;
    run_cycles(cycles: number): void;
    
    // Register access
    get_pc(): number;
    set_pc(value: number): void;
    get_sp(): number;
    set_sp(value: number): void;
    get_a(): number;
    set_a(value: number): void;
    get_x(): number;
    set_x(value: number): void;
    get_y(): number;
    set_y(value: number): void;
    get_sr(): number;
    set_sr(value: number): void;
    
    // Memory operations
    read_memory(address: number): number;
    write_memory(address: number, value: number): void;
    read_memory_range(start: number, length: number): Uint8Array;
    write_memory_range(start: number, data: Uint8Array): void;
    
    // State management
    get_cycles(): bigint;
    
    // Debugging
    add_breakpoint(address: number): void;
    remove_breakpoint(address: number): void;
    clear_breakpoints(): void;
    has_breakpoint(address: number): boolean;
    get_breakpoints(): Uint16Array;
}

/**
 * Initialize the WASM module
 */
export default function init(
    input?: string | URL | Request | BufferSource | WebAssembly.Module
): Promise<InitOutput>;