#!/bin/bash
# Protect generated files from being edited
# Exit 2 = BLOCK the operation
# Exit 0 = ALLOW the operation

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.filePath // empty')

# If we couldn't extract a file path, allow the operation
if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Block edits to generated WASM files
if echo "$FILE_PATH" | grep -qE 'src/wasm/.*\.(js|ts|wasm)$'; then
  echo "BLOCKED: Cannot edit generated WASM files in src/wasm/" >&2
  echo "These files are auto-generated by wasm-pack. Edit the Rust source in wasm-cpu/ instead." >&2
  exit 2
fi

# Allow all other edits
exit 0
